FILE_STATUS_FINISHED = 0
FILE_STATUS_OFFLINE = 1
FILE_STATUS_ONLINE = 2
FILE_STATUS_QUEUED = 3
FILE_STATUS_SKIPPED = 4
FILE_STATUS_WAITING = 5
FILE_STATUS_TEMPORARILY_OFFLINE = 6
FILE_STATUS_STARTING = 7
FILE_STATUS_FAILED = 8
FILE_STATUS_ABORTED = 9
FILE_STATUS_DECRYPTING = 10
FILE_STATUS_CUSTOM = 11
FILE_STATUS_DOWNLOADING = 12
FILE_STATUS_PROCESSING = 13
FILE_STATUS_UNKNOWN = 14

FILE_STATUS_MESSAGES = {
    FILE_STATUS_FINISHED: _("finished"),
    FILE_STATUS_OFFLINE: _("offline"),
    FILE_STATUS_ONLINE: _("online"),
    FILE_STATUS_QUEUED: _("queued"),
    FILE_STATUS_SKIPPED: _("skipped"),
    FILE_STATUS_WAITING: _("waiting"),
    FILE_STATUS_TEMPORARILY_OFFLINE: _("temp. offline"),
    FILE_STATUS_STARTING: _("starting"),
    FILE_STATUS_FAILED: _("failed"),
    FILE_STATUS_ABORTED: _("aborted"),
    FILE_STATUS_DECRYPTING: _("decrypting"),
    FILE_STATUS_CUSTOM: _("custom"),
    FILE_STATUS_DOWNLOADING: _("downloading"),
    FILE_STATUS_PROCESSING: _("processing"),
    FILE_STATUS_UNKNOWN: _("unknown")
}
