#
# Autogenerated by Thrift Compiler (0.9.0-dev)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py:slots,dynamic
#

from __future__ import (
    absolute_import,
    division,
    print_function,
    unicode_literals,
)

from thrift.Thrift import (
    TException,
    TMessageType,
    TType,
)

from .ttypes import *
